version: '3.3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
      - supervisor
    networks:
      - api_network
  php:
    build:
      context: .
      dockerfile: .docker/php.Dockerfile
      args: 
        GUID: 1000
        USER: laravel
    container_name: php
    volumes:
      - .:/var/www/html
      - .docker/php/php-fpm.d:/etc/php7/php-fpm.d
      - .docker/php/php-fpm.conf:/etc/php7/php-fpm.conf
      - .docker/php/php.ini:/etc/php7/php.ini
    working_dir: /var/www/html
    tty: true
    expose:
      - "9000"
    networks:
      - api_network
  supervisor:
    build:
      context: .
      dockerfile: .docker/supervisor.Dockerfile
      args: 
        GUID: 1000
        USER: laravel
    volumes:
        - .:/var/www/html
        - .docker/supervisor/supervisord.d:/etc/supervisord.d
        - .docker/supervisor/supervisord.conf:/etc/supervisord.conf
    networks:
      - api_network
  mysql:
    image: mysql:5.7.34
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: countries_api_database
      MYSQL_USER: countries_api
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      # - .docker/mysql/data:/var/lib/mysql # Uncomment to persist data on disk
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - api_network
  composer:
    build:
      context: .
      dockerfile: .docker/composer.Dockerfile
      args: 
        GUID: 1000
        USER: laravel
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - api_network
  artisan:
    build:
      context: .
      dockerfile: .docker/php.Dockerfile
      args: 
        GUID: 1000
        USER: laravel
    container_name: artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - api_network
  npm:
    image: node:14-alpine3.13
    volumes:
        - .:/app
    working_dir: /app
    entrypoint: ["npm"]
  test:
    build:
      context: .
      dockerfile: .docker/php.Dockerfile
      args: 
        GUID: 1000
        USER: laravel
    container_name: artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/vendor/bin/phpunit']
    networks:
      - api_network
# Docker Networks
networks:
  api_network:
    driver: bridge
# Volumes
volumes:
  data:
    driver: local
